[general]
    import = ["colors.toml",]
[window]
    dynamic_padding = true
    opacity = 0.75
    decorations = "None"
    blur = true
[font]
    normal = { family = "JetBrainsMono Nerd Font"}    
    bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
    italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
    bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
    size = 18.0

