theme = "catppuccin_mocha"


[editor]
line-number = "relative"


[editor.statusline]
left   = ["mode", "separator", "diagnostics", "separator", "file-name"]
center = [ "separator", "version-control", "separator"]
right = [ "file-type", ]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = "|"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
S-r = [":config-reload"] 
y = "yank_joined_to_clipboard"
